using System.Collections.Generic;
using System.Linq;
using SW = SeanWelton;

public static class LocationGenerator
{

    private static readonly NarrativeLocation[] narrativeLocations = new NarrativeLocation[]
    {
        #region Notable Towns & Castle Cities
        new NarrativeLocation { Name = "Kyoto", Tags = new List<LocationTag> { LocationTag.Urban, LocationTag.Flatland, LocationTag.Temple, LocationTag.River } },
        new NarrativeLocation { Name = "Edo", Tags = new List<LocationTag> { LocationTag.Urban, LocationTag.Flatland, LocationTag.Castle, LocationTag.River } },
        new NarrativeLocation { Name = "Osaka", Tags = new List < LocationTag > { LocationTag.Urban, LocationTag.Flatland, LocationTag.Coast, LocationTag.River } },
        new NarrativeLocation { Name = "Nagoya", Tags = new List<LocationTag> { LocationTag.Urban, LocationTag.Flatland, LocationTag.Castle } },
        new NarrativeLocation { Name = "Kanazawa", Tags = new List < LocationTag > { LocationTag.Urban, LocationTag.Flatland, LocationTag.Castle, LocationTag.River } },
        new NarrativeLocation { Name = "Himeji", Tags = new List < LocationTag > { LocationTag.Urban, LocationTag.Flatland, LocationTag.Castle } },
        new NarrativeLocation { Name = "Hikone", Tags = new List < LocationTag > { LocationTag.Urban, LocationTag.Flatland, LocationTag.Castle, LocationTag.River } },
        new NarrativeLocation { Name = "Azuchi", Tags = new List<LocationTag> { LocationTag.Suburban, LocationTag.Flatland, LocationTag.Castle, LocationTag.River } },
        new NarrativeLocation { Name = "Odawara", Tags = new List<LocationTag> { LocationTag.Suburban, LocationTag.Coast, LocationTag.Castle, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Hachioji", Tags = new List<LocationTag> { LocationTag.Suburban, LocationTag.Mountain, LocationTag.Castle } },
        new NarrativeLocation { Name = "Sendai", Tags = new List < LocationTag > { LocationTag.Urban, LocationTag.Flatland, LocationTag.Castle, LocationTag.River } },
        new NarrativeLocation { Name = "Kumamoto", Tags = new List < LocationTag > { LocationTag.Urban, LocationTag.Flatland, LocationTag.Castle } },
        new NarrativeLocation { Name = "Kagoshima", Tags = new List<LocationTag> { LocationTag.Urban, LocationTag.Coast, LocationTag.Castle, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Sakamoto", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Mountain, LocationTag.Temple, LocationTag.Forest } },
        new NarrativeLocation { Name = "Matsuyama", Tags = new List<LocationTag> { LocationTag.Urban, LocationTag.Coast, LocationTag.Castle, LocationTag.Flatland } },
        new NarrativeLocation { Name = "Matsue", Tags = new List<LocationTag> { LocationTag.Urban, LocationTag.Castle, LocationTag.River, LocationTag.Flatland } },
        new NarrativeLocation { Name = "Tsuruga", Tags = new List<LocationTag> { LocationTag.Suburban, LocationTag.Coast, LocationTag.Flatland } },
        new NarrativeLocation { Name = "Uji", Tags = new List<LocationTag> { LocationTag.Suburban, LocationTag.Temple, LocationTag.River, LocationTag.Flatland } },
        new NarrativeLocation { Name = "Nara", Tags = new List<LocationTag> { LocationTag.Urban, LocationTag.Temple, LocationTag.Flatland, LocationTag.Forest } },
        new NarrativeLocation { Name = "Kamakura", Tags = new List<LocationTag> { LocationTag.Urban, LocationTag.Coast, LocationTag.Temple, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Kofu", Tags = new List < LocationTag > { LocationTag.Urban, LocationTag.Flatland, LocationTag.Castle, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Mito", Tags = new List < LocationTag > { LocationTag.Urban, LocationTag.Flatland, LocationTag.Castle, LocationTag.River } },
        new NarrativeLocation { Name = "Niigata", Tags = new List < LocationTag > { LocationTag.Urban, LocationTag.Coast, LocationTag.River, LocationTag.Flatland } },
        new NarrativeLocation { Name = "Wakayama", Tags = new List<LocationTag> { LocationTag.Urban, LocationTag.Coast, LocationTag.Castle, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Fukuyama", Tags = new List<LocationTag> { LocationTag.Urban, LocationTag.Coast, LocationTag.Castle, LocationTag.Flatland } },
        new NarrativeLocation { Name = "Okayama", Tags = new List < LocationTag > { LocationTag.Urban, LocationTag.Flatland, LocationTag.Castle, LocationTag.River } },
        new NarrativeLocation { Name = "Fukui", Tags = new List < LocationTag > { LocationTag.Urban, LocationTag.Flatland, LocationTag.Castle, LocationTag.River } },
        new NarrativeLocation { Name = "Aizuwakamatsu", Tags = new List<LocationTag> { LocationTag.Urban, LocationTag.Mountain, LocationTag.Castle, LocationTag.River } },
        new NarrativeLocation { Name = "Iga-Ueno", Tags = new List<LocationTag> { LocationTag.Suburban, LocationTag.Mountain, LocationTag.Castle, LocationTag.Forest } },
        new NarrativeLocation { Name = "Iwakuni", Tags = new List<LocationTag> { LocationTag.Suburban, LocationTag.River, LocationTag.Mountain, LocationTag.Castle } },
        new NarrativeLocation { Name = "Matsumoto", Tags = new List<LocationTag> { LocationTag.Urban, LocationTag.Castle, LocationTag.Mountain, LocationTag.Flatland } },
        new NarrativeLocation { Name = "Nagahama", Tags = new List<LocationTag> { LocationTag.Suburban, LocationTag.River, LocationTag.Flatland, LocationTag.Castle } },
        new NarrativeLocation { Name = "Tottori", Tags = new List<LocationTag> { LocationTag.Urban, LocationTag.Mountain, LocationTag.Castle, LocationTag.Flatland } },
        new NarrativeLocation { Name = "Toyama", Tags = new List < LocationTag > { LocationTag.Urban, LocationTag.Flatland, LocationTag.Coast, LocationTag.River } },
        new NarrativeLocation { Name = "Takamatsu", Tags = new List<LocationTag> { LocationTag.Urban, LocationTag.Coast, LocationTag.Castle, LocationTag.Flatland } },
        new NarrativeLocation { Name = "Kochi", Tags = new List<LocationTag> { LocationTag.Urban, LocationTag.Coast, LocationTag.Castle, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Saga", Tags = new List < LocationTag > { LocationTag.Urban, LocationTag.Flatland, LocationTag.Castle } },
        new NarrativeLocation { Name = "Utsunomiya", Tags = new List < LocationTag > { LocationTag.Urban, LocationTag.Flatland, LocationTag.Castle } },
        new NarrativeLocation { Name = "Maebashi", Tags = new List < LocationTag > { LocationTag.Urban, LocationTag.Flatland, LocationTag.River } },
        new NarrativeLocation { Name = "Shibata", Tags = new List<LocationTag> { LocationTag.Suburban, LocationTag.Flatland, LocationTag.Castle, LocationTag.River } },
        new NarrativeLocation { Name = "Kunohe", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Mountain, LocationTag.Forest } },
        new NarrativeLocation { Name = "Akashi", Tags = new List<LocationTag> { LocationTag.Suburban, LocationTag.Coast, LocationTag.Castle, LocationTag.Flatland } },
        new NarrativeLocation { Name = "Karatsu", Tags = new List<LocationTag> { LocationTag.Suburban, LocationTag.Coast, LocationTag.Castle } },
        new NarrativeLocation { Name = "Hagi", Tags = new List<LocationTag> { LocationTag.Suburban, LocationTag.Coast, LocationTag.Castle, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Kuroishi", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Mountain, LocationTag.Forest } },
        new NarrativeLocation { Name = "Fukushima", Tags = new List < LocationTag > { LocationTag.Urban, LocationTag.Flatland, LocationTag.Castle } },
        new NarrativeLocation { Name = "Uwajima", Tags = new List<LocationTag> { LocationTag.Suburban, LocationTag.Coast, LocationTag.Castle, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Izushi", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Mountain, LocationTag.Castle, LocationTag.Forest } },
        new NarrativeLocation { Name = "Maruoka", Tags = new List<LocationTag> { LocationTag.Suburban, LocationTag.Flatland, LocationTag.Castle } },
        new NarrativeLocation { Name = "Usuki", Tags = new List<LocationTag> { LocationTag.Suburban, LocationTag.Coast, LocationTag.Castle } },
        new NarrativeLocation { Name = "Uwase", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Mountain, LocationTag.Forest } },
        new NarrativeLocation { Name = "Tsuyama", Tags = new List<LocationTag> { LocationTag.Suburban, LocationTag.Mountain, LocationTag.Castle } },
        new NarrativeLocation { Name = "Kakegawa", Tags = new List<LocationTag> { LocationTag.Suburban, LocationTag.Flatland, LocationTag.Castle } },
        new NarrativeLocation { Name = "Kashiwazaki", Tags = new List<LocationTag> { LocationTag.Suburban, LocationTag.Coast, LocationTag.Flatland } },
        new NarrativeLocation { Name = "Hachinohe", Tags = new List<LocationTag> { LocationTag.Suburban, LocationTag.Coast, LocationTag.Castle } },
        new NarrativeLocation { Name = "Morioka", Tags = new List<LocationTag> { LocationTag.Urban, LocationTag.Mountain, LocationTag.River, LocationTag.Castle } },
        new NarrativeLocation { Name = "Komatsu", Tags = new List<LocationTag> { LocationTag.Suburban, LocationTag.Flatland, LocationTag.River } },
        new NarrativeLocation { Name = "Takeda", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Mountain, LocationTag.Castle } },
        new NarrativeLocation { Name = "Toyama-jo", Tags = new List < LocationTag > { LocationTag.Urban, LocationTag.Flatland, LocationTag.Coast, LocationTag.Castle } },
        new NarrativeLocation { Name = "Yamagata", Tags = new List<LocationTag> { LocationTag.Urban, LocationTag.Mountain, LocationTag.Flatland, LocationTag.Castle } },
        new NarrativeLocation { Name = "Toyooka", Tags = new List<LocationTag> { LocationTag.Suburban, LocationTag.Flatland, LocationTag.River } },
        new NarrativeLocation { Name = "Kanoya", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Mountain, LocationTag.Flatland } },
        new NarrativeLocation { Name = "Nishio", Tags = new List<LocationTag> { LocationTag.Suburban, LocationTag.Flatland, LocationTag.Castle } },
        new NarrativeLocation { Name = "Obama", Tags = new List<LocationTag> { LocationTag.Suburban, LocationTag.Coast, LocationTag.Flatland } },
        new NarrativeLocation { Name = "Anotsu", Tags = new List<LocationTag> { LocationTag.Suburban, LocationTag.Coast, LocationTag.River } },
        new NarrativeLocation { Name = "Shizuoka", Tags = new List < LocationTag > { LocationTag.Urban, LocationTag.Flatland, LocationTag.River, LocationTag.Castle } },
        new NarrativeLocation { Name = "Gifu", Tags = new List < LocationTag > { LocationTag.Urban, LocationTag.Flatland, LocationTag.River, LocationTag.Castle } },
        new NarrativeLocation { Name = "Nagakute", Tags = new List<LocationTag> { LocationTag.Suburban, LocationTag.Flatland } },
        new NarrativeLocation { Name = "Komoro", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Mountain, LocationTag.Castle } },
        new NarrativeLocation { Name = "Sakai", Tags = new List<LocationTag> { LocationTag.Urban, LocationTag.Coast, LocationTag.Flatland } },
        new NarrativeLocation { Name = "Fujisawa", Tags = new List<LocationTag> { LocationTag.Suburban, LocationTag.Coast, LocationTag.Flatland } },
        new NarrativeLocation { Name = "Maizuru", Tags = new List<LocationTag> { LocationTag.Suburban, LocationTag.Coast, LocationTag.Castle } },
        new NarrativeLocation { Name = "Kochi", Tags = new List<LocationTag> { LocationTag.Urban, LocationTag.Coast, LocationTag.Castle, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Kameyama", Tags = new List<LocationTag> { LocationTag.Suburban, LocationTag.Mountain, LocationTag.Castle } },
        new NarrativeLocation { Name = "Suwa", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Mountain, LocationTag.River, LocationTag.Temple } },
        new NarrativeLocation { Name = "Murakami", Tags = new List<LocationTag> { LocationTag.Suburban, LocationTag.Coast, LocationTag.Castle } },
        new NarrativeLocation { Name = "Takatsu", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.River, LocationTag.Flatland } },
        new NarrativeLocation { Name = "Ushiku", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Flatland } },
        new NarrativeLocation { Name = "Matsusaka", Tags = new List<LocationTag> { LocationTag.Suburban, LocationTag.Flatland, LocationTag.Castle } },
        new NarrativeLocation { Name = "Yonezawa", Tags = new List<LocationTag> { LocationTag.Suburban, LocationTag.Mountain, LocationTag.Castle } },
        new NarrativeLocation { Name = "Yamaguchi", Tags = new List < LocationTag > { LocationTag.Urban, LocationTag.Flatland, LocationTag.Temple } },
        new NarrativeLocation { Name = "Tsu", Tags = new List < LocationTag > { LocationTag.Urban, LocationTag.Flatland, LocationTag.Coast, LocationTag.Castle } },
        new NarrativeLocation { Name = "Hita", Tags = new List<LocationTag> { LocationTag.Suburban, LocationTag.Mountain, LocationTag.River } },
        new NarrativeLocation { Name = "Miyazu", Tags = new List<LocationTag> { LocationTag.Suburban, LocationTag.Coast, LocationTag.Temple } },
        new NarrativeLocation { Name = "Karuizawa", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Mountain, LocationTag.Forest } },
        new NarrativeLocation { Name = "Shimonoseki", Tags = new List<LocationTag> { LocationTag.Urban, LocationTag.Coast, LocationTag.Castle } },
        new NarrativeLocation { Name = "Kaseda", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Flatland, LocationTag.Coast } },
        new NarrativeLocation { Name = "Nobeoka", Tags = new List<LocationTag> { LocationTag.Suburban, LocationTag.Mountain, LocationTag.River, LocationTag.Castle } },
        new NarrativeLocation { Name = "Saiki", Tags = new List<LocationTag> { LocationTag.Suburban, LocationTag.Coast, LocationTag.Castle } },
        new NarrativeLocation { Name = "Ozu", Tags = new List<LocationTag> { LocationTag.Suburban, LocationTag.River, LocationTag.Castle } },
        new NarrativeLocation { Name = "Koriyama", Tags = new List < LocationTag > { LocationTag.Urban, LocationTag.Flatland, LocationTag.Castle } },
        #endregion

        #region Historical Provinces
        new NarrativeLocation { Name = "Aki", Tags = new List<LocationTag> { LocationTag.Suburban, LocationTag.Coast, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Awa (Shikoku)", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Mountain, LocationTag.Coast } },
        new NarrativeLocation { Name = "Awa (Boso)", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Coast, LocationTag.Flatland } },
        new NarrativeLocation { Name = "Awaji", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Island, LocationTag.Mountain, LocationTag.Coast } },
        new NarrativeLocation { Name = "Bizen", Tags = new List<LocationTag> { LocationTag.Suburban, LocationTag.Flatland, LocationTag.Coast } },
        new NarrativeLocation { Name = "Bingo", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Mountain, LocationTag.Flatland } },
        new NarrativeLocation { Name = "Buzen", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Mountain, LocationTag.Coast } },
        new NarrativeLocation { Name = "Chubu", Tags = new List<LocationTag> { LocationTag.Suburban, LocationTag.Mountain, LocationTag.Flatland } },
        new NarrativeLocation { Name = "Dewa", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Mountain, LocationTag.Forest } },
        new NarrativeLocation { Name = "Echigo", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Mountain, LocationTag.Flatland } },
        new NarrativeLocation { Name = "Echizen", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Mountain, LocationTag.Coast } },
        new NarrativeLocation { Name = "Hida", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Mountain, LocationTag.Forest } },
        new NarrativeLocation { Name = "Higo", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Mountain, LocationTag.Flatland } },
        new NarrativeLocation { Name = "Hitachi", Tags = new List<LocationTag> { LocationTag.Suburban, LocationTag.Flatland, LocationTag.Coast } },
        new NarrativeLocation { Name = "Hizen", Tags = new List<LocationTag> { LocationTag.Suburban, LocationTag.Coast, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Hyuga", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Coast, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Iga", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Mountain, LocationTag.Forest } },
        new NarrativeLocation { Name = "Iki", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Island, LocationTag.Coast } },
        new NarrativeLocation { Name = "Ise", Tags = new List<LocationTag> { LocationTag.Suburban, LocationTag.Flatland, LocationTag.Temple } },
        new NarrativeLocation { Name = "Izu", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Mountain, LocationTag.Coast } },
        new NarrativeLocation { Name = "Iyo", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Coast, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Izumo", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Flatland, LocationTag.Temple } },
        new NarrativeLocation { Name = "Kaga", Tags = new List<LocationTag> { LocationTag.Suburban, LocationTag.Flatland, LocationTag.Coast } },
        new NarrativeLocation { Name = "Kii", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Mountain, LocationTag.Coast, LocationTag.Forest } },
        new NarrativeLocation { Name = "Kai", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Kawachi", Tags = new List<LocationTag> { LocationTag.Suburban, LocationTag.Flatland } },
        new NarrativeLocation { Name = "Kazusa", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Flatland, LocationTag.Coast } },
        new NarrativeLocation { Name = "Kozuke", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Mountain, LocationTag.Flatland } },
        new NarrativeLocation { Name = "Mimasaka", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Mountain, LocationTag.Forest } },
        new NarrativeLocation { Name = "Mikawa", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Flatland, LocationTag.River } },
        new NarrativeLocation { Name = "Mutsu", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Mountain, LocationTag.Forest, LocationTag.Coast } },
        new NarrativeLocation { Name = "Musashi", Tags = new List<LocationTag> { LocationTag.Suburban, LocationTag.Flatland, LocationTag.River } },
        new NarrativeLocation { Name = "Nagato", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Coast, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Noto", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Coast, LocationTag.Mountain, LocationTag.Forest } },
        new NarrativeLocation { Name = "Omi", Tags = new List<LocationTag> { LocationTag.Suburban, LocationTag.Flatland, LocationTag.River } },
        new NarrativeLocation { Name = "Owari", Tags = new List<LocationTag> { LocationTag.Suburban, LocationTag.Flatland, LocationTag.River } },
        new NarrativeLocation { Name = "Rikuchu", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Mountain, LocationTag.Forest, LocationTag.Coast } },
        new NarrativeLocation { Name = "Rikuzen", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Mountain, LocationTag.Forest, LocationTag.Coast } },
        new NarrativeLocation { Name = "Sagami", Tags = new List<LocationTag> { LocationTag.Suburban, LocationTag.Flatland, LocationTag.Coast, LocationTag.River } },
        new NarrativeLocation { Name = "Satsuma", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Mountain, LocationTag.Coast, LocationTag.Forest } },
        new NarrativeLocation { Name = "Settsu", Tags = new List < LocationTag > { LocationTag.Urban, LocationTag.Flatland, LocationTag.Coast, LocationTag.River } },
        new NarrativeLocation { Name = "Shimosa", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Flatland, LocationTag.Coast } },
        new NarrativeLocation { Name = "Shima", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Island, LocationTag.Coast } },
        new NarrativeLocation { Name = "Shinano", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Mountain, LocationTag.Forest, LocationTag.River } },
        new NarrativeLocation { Name = "Totomi", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Flatland, LocationTag.Coast } },
        new NarrativeLocation { Name = "Tsushima", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Island, LocationTag.Coast, LocationTag.Mountain, LocationTag.Forest } },
        new NarrativeLocation { Name = "Ugo", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Mountain, LocationTag.Forest } },
        new NarrativeLocation { Name = "Wakasa", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Coast, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Yamashiro", Tags = new List<LocationTag> { LocationTag.Urban, LocationTag.Mountain, LocationTag.Temple } },
        new NarrativeLocation { Name = "Yamato", Tags = new List<LocationTag> { LocationTag.Suburban, LocationTag.Mountain, LocationTag.Temple } },
        #endregion

        #region Shinto Shrines
        new NarrativeLocation { Name = "Ise Grand Shrine", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Temple, LocationTag.Flatland } },
        new NarrativeLocation { Name = "Izumo Taisha", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Temple, LocationTag.Flatland } },
        new NarrativeLocation { Name = "Kashima Shrine", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Temple, LocationTag.Coast } },
        new NarrativeLocation { Name = "Katori Shrine", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Temple, LocationTag.Flatland } },
        new NarrativeLocation { Name = "Fushimi Inari Shrine", Tags = new List<LocationTag> { LocationTag.Suburban, LocationTag.Temple, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Shimogamo Shrine", Tags = new List<LocationTag> { LocationTag.Urban, LocationTag.Temple, LocationTag.Forest } },
        new NarrativeLocation { Name = "Kamigamo Shrine", Tags = new List<LocationTag> { LocationTag.Urban, LocationTag.Temple, LocationTag.Forest } },
        new NarrativeLocation { Name = "Nikko Futarasan Shrine", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Temple, LocationTag.Mountain, LocationTag.Forest } },
        new NarrativeLocation { Name = "Toshogu Shrine (Nikko)", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Temple, LocationTag.Mountain, LocationTag.Forest } },
        new NarrativeLocation { Name = "Usa Jingu", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Temple, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Oyama Shrine", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Temple, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Miho Shrine", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Temple, LocationTag.Coast } },
        new NarrativeLocation { Name = "Munakata Taisha", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Temple, LocationTag.Island, LocationTag.Coast } },
        new NarrativeLocation { Name = "Suwa Shrine", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Temple, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Kasuga Taisha", Tags = new List<LocationTag> { LocationTag.Urban, LocationTag.Temple, LocationTag.Forest } },
        new NarrativeLocation { Name = "Taga Taisha", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Temple, LocationTag.Flatland } },
        new NarrativeLocation { Name = "Umenomiya Shrine", Tags = new List<LocationTag> { LocationTag.Suburban, LocationTag.Temple, LocationTag.Flatland } },
        new NarrativeLocation { Name = "Tsurugaoka Hachimangu", Tags = new List<LocationTag> { LocationTag.Urban, LocationTag.Temple } },
        new NarrativeLocation { Name = "Hie Shrine", Tags = new List<LocationTag> { LocationTag.Urban, LocationTag.Temple, LocationTag.Flatland } },
        new NarrativeLocation { Name = "Ikoma Shrine", Tags = new List<LocationTag> { LocationTag.Suburban, LocationTag.Temple, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Atsuta Shrine", Tags = new List<LocationTag> { LocationTag.Urban, LocationTag.Temple, LocationTag.Flatland } },
        new NarrativeLocation { Name = "Kumano Hayatama Shrine", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Temple, LocationTag.Coast, LocationTag.Forest } },
        new NarrativeLocation { Name = "Kumano Hongu Shrine", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Temple, LocationTag.Mountain, LocationTag.Forest } },
        new NarrativeLocation { Name = "Kumano Nachi Shrine", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Temple, LocationTag.Mountain, LocationTag.Forest, LocationTag.Coast } },
        new NarrativeLocation { Name = "Hiraoka Shrine", Tags = new List<LocationTag> { LocationTag.Suburban, LocationTag.Temple, LocationTag.Flatland } },
        new NarrativeLocation { Name = "Oyamazumi Shrine", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Temple, LocationTag.Island, LocationTag.Coast } },
        new NarrativeLocation { Name = "Hieda Shrine", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Temple, LocationTag.Flatland } },
        #endregion

        #region Buddhist Temples & Pilgrimage Complexes
        new NarrativeLocation { Name = "Enryaku-ji", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Temple, LocationTag.Mountain, LocationTag.Forest } },
        new NarrativeLocation { Name = "Kongobu-ji", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Temple, LocationTag.Mountain, LocationTag.Forest } },
        new NarrativeLocation { Name = "Todaiji", Tags = new List<LocationTag> { LocationTag.Urban, LocationTag.Temple, LocationTag.Flatland } },
        new NarrativeLocation { Name = "Kofuku-ji", Tags = new List<LocationTag> { LocationTag.Urban, LocationTag.Temple, LocationTag.Flatland } },
        new NarrativeLocation { Name = "Yakushi-ji", Tags = new List<LocationTag> { LocationTag.Urban, LocationTag.Temple, LocationTag.Flatland } },
        new NarrativeLocation { Name = "Horyu-ji", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Temple, LocationTag.Flatland } },
        new NarrativeLocation { Name = "Byodoin", Tags = new List<LocationTag> { LocationTag.Suburban, LocationTag.Temple, LocationTag.Flatland } },
        new NarrativeLocation { Name = "Kiyomizu-dera", Tags = new List<LocationTag> { LocationTag.Urban, LocationTag.Temple, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Koyasan Danjo Garan", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Temple, LocationTag.Mountain, LocationTag.Forest } },
        new NarrativeLocation { Name = "Mii-dera", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Temple, LocationTag.Flatland } },
        new NarrativeLocation { Name = "Zenko-ji", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Temple, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Saifuku-ji", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Temple, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Iwashimizu Hachiman Shrine & Temple", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Temple, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Kouzen-ji", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Temple, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Daigo-ji", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Temple, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Tosho-ji", Tags = new List<LocationTag> { LocationTag.Urban, LocationTag.Temple, LocationTag.Flatland } },
        new NarrativeLocation { Name = "Shorin-ji", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Temple, LocationTag.Forest } },
        new NarrativeLocation { Name = "Saiho-ji", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Temple, LocationTag.Forest } },
        new NarrativeLocation { Name = "Jingo-ji", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Temple, LocationTag.Mountain, LocationTag.Forest } },
        new NarrativeLocation { Name = "Tokaku-ji", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Temple, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Hoon-in", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Temple, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Shinsho-ji", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Temple, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Hosshin-ji", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Temple, LocationTag.Mountain } },
        #endregion

        #region Mountains & Peaks
        new NarrativeLocation { Name = "Mount Fuji", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Mount Hiei", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Mount Koya", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Mount Haguro", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Mount Gassan", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Mount Yudono", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Mount Tate", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Mount Hotaka", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Mount Norikura", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Mount Asama", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Mount Aso", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Mount Daisen", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Mount Kasagi", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Mount Yoshino", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Mount Kiso Ontake", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Mount Omine", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Mount Kumano", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Mount Hakusan", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Mount Tsukuba", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Mount Myogi", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Mount Bandai", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Mount Iwaki", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Mount Azuma", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Mount Chokai", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Mount Nasu", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Mount Yoro", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Mount Rishiri", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Mountain, LocationTag.Island } },
        new NarrativeLocation { Name = "Mount Dewa", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Mount Akagi", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Mount Takao", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Mount Mitake", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Mount Ibuki", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Mount Tateyama", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Mount Aizu Bandai", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Mount Bessan", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Mountain } },
        #endregion

        #region Rivers & Valleys
        new NarrativeLocation { Name = "Kiso Valley", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Forest, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Tama River", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.River, LocationTag.Flatland } },
        new NarrativeLocation { Name = "Yodo River", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.River, LocationTag.Flatland } },
        new NarrativeLocation { Name = "Shinano River", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.River, LocationTag.Mountain, LocationTag.Flatland } },
        new NarrativeLocation { Name = "Tone River", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.River, LocationTag.Flatland } },
        new NarrativeLocation { Name = "Kurokawa Gorge", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Forest, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Oirase Stream", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.River, LocationTag.Forest } },
        new NarrativeLocation { Name = "Kamo River", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.River, LocationTag.Flatland } },
        new NarrativeLocation { Name = "Kumano River", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.River, LocationTag.Forest } },
        new NarrativeLocation { Name = "Nishiki River", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.River, LocationTag.Forest } },
        new NarrativeLocation { Name = "Kitayama Valley", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Forest, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Oi River", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.River, LocationTag.Mountain, LocationTag.Forest } },
        new NarrativeLocation { Name = "Sendai River", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.River, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Amanogawa (Ama River)", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.River, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Katsura River", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.River, LocationTag.Forest } },
        new NarrativeLocation { Name = "Yoshino River", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.River, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Totsukawa Valley", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Mountain, LocationTag.Forest } },
        new NarrativeLocation { Name = "Chikugo River", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.River, LocationTag.Flatland } },
        new NarrativeLocation { Name = "Ibi River", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.River, LocationTag.Flatland } },
        new NarrativeLocation { Name = "Nagura River", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.River, LocationTag.Mountain, LocationTag.Forest } },
        new NarrativeLocation { Name = "Amano Valley", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Mountain, LocationTag.Forest } },
        new NarrativeLocation { Name = "Kiso River", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.River, LocationTag.Mountain, LocationTag.Forest } },
        new NarrativeLocation { Name = "Hozu River", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.River, LocationTag.Forest, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Naka River", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.River, LocationTag.Flatland } },
        new NarrativeLocation { Name = "Agano River", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.River, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Tenryu River", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.River, LocationTag.Mountain, LocationTag.Forest } },
        new NarrativeLocation { Name = "Kashima River", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.River, LocationTag.Flatland } },
        new NarrativeLocation { Name = "Sho River", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.River, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Sagami River", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.River, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Ono River", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.River, LocationTag.Forest } },
        #endregion

        #region Coastal & Maritime Areas
        new NarrativeLocation { Name = "Ise Bay", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Coast, LocationTag.Flatland } },
        new NarrativeLocation { Name = "Osaka Bay", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Coast, LocationTag.Flatland } },
        new NarrativeLocation { Name = "Tokyo Bay", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Coast, LocationTag.Flatland } },
        new NarrativeLocation { Name = "Wakasa Bay", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Coast, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Tosa Bay", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Coast, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Suruga Bay", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Coast, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Hiroshima Bay", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Coast, LocationTag.Flatland } },
        new NarrativeLocation { Name = "Kagoshima Bay", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Coast, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Ariake Sea", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Coast, LocationTag.Flatland } },
        new NarrativeLocation { Name = "Yatsushiro Sea", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Coast, LocationTag.Flatland } },
        new NarrativeLocation { Name = "Bungo Channel", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Coast, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Kanmon Straits", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Coast, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Seto Inland Sea", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Coast, LocationTag.Island } },
        new NarrativeLocation { Name = "Pacific Coast of Tokai", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Coast, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Noto Peninsula", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Coast, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Kii Peninsula", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Coast, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Shima Peninsula", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Coast, LocationTag.Forest } },
        new NarrativeLocation { Name = "Nemuro Strait", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Coast, LocationTag.Island } },
        new NarrativeLocation { Name = "Satsuma Peninsula", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Coast, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Oga Peninsula", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Coast, LocationTag.Mountain } },
        new NarrativeLocation { Name = "Boso Peninsula", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Coast, LocationTag.Forest } },
        new NarrativeLocation { Name = "Osumi Strait", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Coast, LocationTag.Island } },
        new NarrativeLocation { Name = "Chita Peninsula", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Coast, LocationTag.Flatland } },
        new NarrativeLocation { Name = "Awa Coastal Region", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Coast } },
        new NarrativeLocation { Name = "Sanriku Coast", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Coast, LocationTag.Forest } },
        new NarrativeLocation { Name = "Iyo Sea", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Coast, LocationTag.Island } },
        new NarrativeLocation { Name = "Iwami Coast", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Coast, LocationTag.Forest } },
        new NarrativeLocation { Name = "Hidaka Coast", Tags = new List<LocationTag> { LocationTag.Rural, LocationTag.Coast, LocationTag.Mountain } },
        #endregion
    };

    public static NarrativeLocation GetRandomOrigin()
    {
        return narrativeLocations[SW.Random.Integer(0, narrativeLocations.Length)];
    }

}